spring:
  main:
    web-application-type: NONE

---
spring:    
  profiles: mysql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
      hibernate.default_batch_fetch_size: ${chunkSize:1000}
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?verifyServerCertificate=false&useSSL=false
    username: test
    password: test
    #hikari:
      #jdbc-url: jdbc:mysql://localhost:3306/test?verifyServerCertificate=false&useSSL=false
      
      #driver-class-name: com.mysql.cj.jdbc.Driver
      